### ISSUE TITLE
Getting error in running it in Visual Code 2019

### ISSUE THREAD

**Issue by harshu729** [cynricfu/huffman-coding#3]
Hi developer,
Can you tell me what software and the environment did you use to build it?
I'm getting like 30 errors in VS Code in building of huffmanCoding.cpp and same errors in building of huffmanDecoding.cpp also.
I'm attaching the screenshot of errors. Please help me in understanding and building of the code.

![Capture](https://user-images.githubusercontent.com/14768535/95602688-e5a0c400-0a72-11eb-846b-b77df0d98ea8.PNG)

**Comment by cynricfu** [comment]
I was using Visual Studio to develop this huffman coding algorithm. But I do not remember the exact version.
